package com.jordanproject.ps.service;

import java.util.List;
import java.util.Random;
import java.util.UUID;

import org.apache.tomcat.util.buf.UDecoder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.jordanproject.ps.dao.PaymentDAO;
import com.jordanproject.ps.model.Payment;

@Service
public class PaymentService {

	@Autowired
	private PaymentDAO paymentDao;
	
	public Payment savePayment(Payment payment) {
//		ID autogenerated
		payment.setTransactionId(UUID.randomUUID().toString());
		payment.setPaymentStatus(true);
		return paymentDao.save(payment);
	}
	
	public List<Payment> getListOfPayments() {
		return paymentDao.findAll();
	}

	public Payment findPaymentHistoryByOrderId(int orderId) {
		// TODO Auto-generated method stub

		return paymentDao.findByOrderId(orderId);
	}
}
